[program:laravel-worker-agregados]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend-core/artisan queue:work redis --queue=agregados --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/backend-core/storage/logs/worker-agregados.log
stopwaitsecs=3600

[program:laravel-worker-imagenes]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend-core/artisan queue:work redis --queue=imagenes --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/backend-core/storage/logs/worker-imagenes.log
stopwaitsecs=3600

[program:laravel-worker-notificaciones]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend-core/artisan queue:work redis --queue=notificaciones --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/backend-core/storage/logs/worker-notificaciones.log
stopwaitsecs=3600

[group:laravel-workers]
programs=laravel-worker-agregados,laravel-worker-imagenes,laravel-worker-notificaciones
